var listquestions =
[
    "What are the values you were brought up with?",
    "What things do you notice trigger your body to tense up?",
    "How do your friends and family describe you?",
    "What do you wish your friends and family knew about you?",
    "What’s something you’re often embarrassed to admit to others?",
    "What are the things you wish you were better at?",
    "If you were to write a memoir about your life, what would the chapter titles be?",
    "What are the three most important relationships in your life, and how have they influenced your beliefs about who you are?",
    "What kind of people do you attract around you?",
    "If you could share a secret about yourself with the world and remain anonymous, what would you share?",
    "Where were you, and what were you doing the last time you felt truly at peace?",
    "What kind of things about yourself make you feel “less than” others?",
    "How do people describe you at work?",
    "What is something people often get wrong about you at work?",
    "What do you wish people knew about you at work?",
    "What would you do differently if you could start your career over again?",
    "What kind of responsibilities drain you at work?",
    "What kind of work requests trigger you negatively? Why do you think that is?",
    "What do you wish you could change about your workplace or career?",
    "Do you wish people treated you differently at work? How so?",
    "What expectations feel hard to live up to at work?",
    "What kind of advice do people come to you for? Why do you think that is?",
    "What expectations feel easy to live up to but don’t feel authentic to who you are?",
    "What skill do you think you might have a knack for but don’t try or talk about because you’re afraid of failing?",
    "When you think about what God’s voice or a higher power might sound like, what do you imagine? What does this voice say about you?",
    "What does it mean to be good? Where do your beliefs about goodness come from?",
    "What does it mean to be evil? Where do your beliefs about evilness come from?",
    "What about your belief system feels hard to trust? Why do you think that is?",
    "What do your spiritual beliefs say about who you are?",
    "If you were to question your beliefs, what do you fear others might think about you?",
    "If you have an inner voice, what does it sound like? Is it kind? Critical? Loving? What does it say about you?",
    "When bad things happen, what does it say about you? What about when good things happen?",
    "What or who has the most influence on your life? Are you OK with this influence?",
    "What gives you the most purpose in life? How can you do more of that?",
    "What makes you feel valued?",
    "What does it feel like when someone oversteps your boundaries? What do you do?",
    "How do you wish others would show up for you?",
    "What makes you feel alone?",
    "What makes you stay in relationships that aren’t good for you?",
    "When was the last time you felt less than? What happened?",
    "What triggers bring out the worst in you? Why?",
    "When you put on a mask to show others a specific version of yourself, what part of you are you trying to hide?",
    "Have you ever broken a promise to yourself? What happened? How did it feel?",
    "What’s one thing you wish you could change about your past?",
    "Are there certain emotions you feel more comfortable with? Why do you think that is?",
    "What’s an idea or story that you cling to when you feel like giving up? What does it say about who you are?",
    "What core memory from your childhood makes you angry?",
    "What core memory from your childhood makes you feel shame?",
    "How did your parent or guardian encourage or discourage you growing up?",
    "What words did others use to describe you growing up?",
    "What did you wish people understood about you growing up?",
    "If you could go back to your elementary-school-aged self, what advice would you give?",
    "What do you wish you could change about how you grew up?",
    "What were you most insecure about growing up?",
    "What was your biggest fear growing up?",
    "What’s something you rarely talk about that happened to you as a child?",
    "What did your parents or guardians ask of you growing up?",
    "Name a time when you felt rejected. What happened?",
    "What does being vulnerable in a relationship look like to you?",
    "When you’re vulnerable with someone, how does it feel? Is it safe? Is it hard? Why?",
    "When was the last time you felt jealous? What did you fear might happen? Why?",
    "Think of a relationship you’ve walked away from. Write down the reasons it’s been a positive life choice.",
    "What makes you feel defensive? What are you trying to protect?",
    "What do you hate most that others do in a relationship? Why?",
    "What is one thing you hope your partner never finds out about you? What might happen if they knew?",
    "When was the last time you forgave someone? Was it hard? Why or why not?",
    "What does my partner get annoyed with me about? What does or doesn’t it say about me?",
    "What do you want our partner to believe and know about you?",
    "What’s something you always wished you could do but haven’t done because you’re afraid?",
    "How do you self-sabotage the things you want in life?",
    "What do you wish you could forgive yourself for? What makes it hard?",
    "What areas of your life give you the most purpose?",
    "What has hurt you the most from your past? What do you wish you had now to heal from that pain?",
    "When was the last time you received compassion? What did that feel like? What does it say about you?",
    "If you fully accepted yourself for who you are, what kinds of things could you stop doing today?",
    "What kind of things do you notice you do to conform to others around you? If you stopped conforming, what would this say about you?",
    "If you said no to something you normally feel obligated to do, what does that free you up to do instead?",
    "What do you believe is true about you? What is not true? What do your beliefs say about who you are?",
    "How do you respond when someone expresses support? Do you reject or accept it? What does your response say about who you are?",
    "What have you done that makes you feel most like a failure?",
    "What do you think others would think if the one thing you feel most shameful about were shared in every ad on YouTube?",
    "What destructive patterns do you notice you repeat? Why do you think you repeat them?",
    "What is the meaning of success to you? Where do you think that comes from?",
    "What does your family mean to you? How have they impacted your life?",
    "What do you have a hard time saying no to that you wish you could let go?",
    "Who in your life takes up the most emotional energy? Why do you think that is?",
    "What habits do you feel guilty or shameful about? Why?",
    "What kind of behaviors in others make you the angriest? Why? What does it say about you?",
    "When was the last time you felt betrayed by someone? What happened? What do you wish they knew about you?",
    "If you found out you would die today, what would you regret not doing in your life?",
    "How do you self-sabotage the things you want in life? What do you wish you’d do instead?",
    "How do you respond when someone is angry with you? What does their anger say about you?",
    "What makes you feel unworthy of love and belonging? Where does this come from?",
    "If you could write a letter to the person(s) who hurt you the most, what would you say?",
    "What do you feel you must do to be worthy of love? Why?",
    "What part of your personality or personhood do you find most challenging to accept? Why?",
    "When was the last time you realized you were wrong about something? How did it make you feel? What did you do about it?",
    "Do you trust yourself? Why or why not? ",
    "When was the last time you stood up for yourself? What were you defending and why?",
    "What kind of things do you do to numb your feelings? What are you trying to avoid?",
    "When you’re alone, what does your self-talk most commonly sound like? What kinds of things do you say to yourself, and why?"
]

function randomizer()
{
    var list1 = Math.floor(Math.random() * listquestions.length);
    $("#prompt").text(listquestions[list1]);
}

randomizer();

$("#bottone").click(function()
{
	randomizer();
});